### ISSUE TITLE
Unable to run smartcomments command

### ISSUE THREAD

**Issue by jacksctsai** [smartcomments/smartcomments#22]
I've used the latest version downloaded from npm install.

However, executing the smartcomments command brought me to this error message:

<pre>
env: node\r: No such file or directory
</pre>

I guess this might due to the incompatibility of its file format (I'm a Mac user.) So I just opened the file (smartcomments alone), copy the entire text and replace it by pasting it back and save. Then everything becomes normal.

**Comment by darielnoel** [comment]
Thanks Jack, for reporting this problem. Unfortunately we are not Mac users and is makes us very difficult to test SmartComments on Mac. I have been reading and apparently this is because the file is in DOS mode. In the following links, we can find the solution. If you want, you can send a pull request with the problem solved. Thanks you very much, for help us.

https://github.com/BlueSpire/Weyland/issues/1

https://github.com/stubbornella/csslint/issues/82

Best Regards, Dariel

**Comment by jacksctsai** [comment]
I've forked the repository and tested and no error happened.
So I guess it is the files being published to npm have problem.
I have no solution to this because I'm not responsible of the publishing process, but I guess cloning the repository to a clean folder and re-publish to npm would solve the problem.

Yours,
-jack

**Comment by darielnoel** [comment]
Hello Jack, Could you please to download SmartComments from this link https://github.com/darielnoel/smartcomments/tree/file2mode and test if the invalid coding problems in Mac has been solved. I will be very grateful. Best Regards

**Comment by jacksctsai** [comment]
Hi darielnoel,

Files from your branch has tested and no problem occurred.

Yours,
-jack

**Comment by darielnoel** [comment]
Hi Jack, we've fixed the problem in the published version in npm. I would be very grateful if you taste it directly using npm on Mac.

npm install-g smartcomments

Thank you very much again and forgive us so much trouble.

Regards, Dariel

**Comment by jacksctsai** [comment]
The npm package has tested and fine.
Thanks for your kindly help. :+1:

**Comment by darielnoel** [comment]
Thank you Jack for being so kind to help us resolve this issue.

Regards
